#!/usr/bin/env bash
set -euo pipefail

# Finalize and validate the npm manifest generated by `deno pack`.
# JSR keeps the scoped deno.json name; npm uses scripts/npm-metadata.json.
# Zod is supplied by the consuming application, so it is a peer dependency.
#
# Usage: scripts/prepare_npm.sh [path/to/schema-xml.tgz]
# Defaults to dist/schema-xml.tgz.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARBALL="${1:-$ROOT/dist/schema-xml.tgz}"

if [[ ! -f "$TARBALL" ]]; then
  echo "error: tarball not found at $TARBALL — run 'deno task pack' first" >&2
  exit 1
fi
TARBALL="$(cd "$(dirname "$TARBALL")" && pwd)/$(basename "$TARBALL")"

WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

tar -xzf "$TARBALL" -C "$WORKDIR"

node --input-type=module - "$WORKDIR/package" "$ROOT" <<'JS'
import assert from "node:assert/strict";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, sep } from "node:path";

const [packageDir, root] = process.argv.slice(2);
const readJson = (path) => JSON.parse(readFileSync(path, "utf8"));
const path = resolve(packageDir, "package.json");
const pkg = readJson(path);
const source = readJson(resolve(root, "deno.json"));
const metadata = readJson(resolve(root, "scripts/npm-metadata.json"));
assert.equal(pkg.name, source.name, "Unexpected source package name");
assert.equal(pkg.version, source.version, "Package version must match deno.json");
const range = pkg.dependencies?.zod;
assert.equal(range, source.imports.zod.replace(/^npm:zod@/, ""));
assert.equal(typeof range, "string", "Zod dependency is missing");
delete pkg.dependencies.zod;
pkg.peerDependencies = { ...pkg.peerDependencies, zod: range };
Object.assign(pkg, metadata);
pkg.license = source.license;

// Fail if test-only or JSR dependencies leak into the npm artifact.
assert.deepEqual(Object.keys(pkg.dependencies).sort(), ["fast-xml-parser"]);
assert.equal(pkg.dependencies["fast-xml-parser"], source.imports["fast-xml-parser"].replace(/^npm:fast-xml-parser@/, ""));
assert.equal(pkg.name, "schema-xml");
assert.equal(pkg.type, "module");
assert.ok(pkg.exports?.["."]?.types, "Declaration export is required");
assert.ok(pkg.exports?.["."]?.import, "ESM export is required");
function checkExports(value) {
  if (typeof value === "string") {
    const target = resolve(packageDir, value);
    assert.ok(value.startsWith("./") && target.startsWith(resolve(packageDir) + sep), "Export must stay inside the package");
    assert.ok(existsSync(target), `Missing export: ${value}`);
  } else {
    for (const child of Object.values(value)) checkExports(child);
  }
}
checkExports(pkg.exports);
for (const file of ["README.md", "LICENSE"]) {
  assert.ok(existsSync(resolve(packageDir, file)), `Missing ${file}`);
}
writeFileSync(path, JSON.stringify(pkg, null, 2) + "\n");
console.log(`Validated ${pkg.name}@${pkg.version} with Zod peer ${range}`);
JS

tar -czf "$TARBALL" -C "$WORKDIR" package
echo "==> npm metadata finalized in $(basename "$TARBALL")"
